allowBuilds:
  esbuild: false
minimumReleaseAgeExclude:
  - '@kubohiroya/vite-plugin-turbowarp-extension@0.3.0'
  - '@kubohiroya/turbowarp-named-functions@0.1.0'
  - '@kubohiroya/turbowarp-openai-realtime-api@0.1.0'
  - '@kubohiroya/turbowarp-web-speech@0.1.0'
